Organiza dados de temperatura do Alerta dengue 
===============================================
Usa dados do OpenWeather, atualmente so' de uma estacao, que e' replicado para
todas as APS

```{r include=FALSE}
#library("lubridate")
#source("../fun/data2SE.r")
#source("../fun/callmongoclima.r")
```

Abre dados OpenWeather (autor: Oswaldo): 
-----------

```{r}
#novoclima <- novosinan <- paste("../",novoclima,sep="")
#d<-read.csv2(novoclima)
#galeao<- read.csv2("http://gtsinan.no-ip.biz:8081/alerta/galeao.csv")
#d <- galeao
#tail(d)
#d$estacao <- "galeao"
#Incluir variavel semana epidemiologica

#d$SE<-data2SE(d$data,file="../tabelas/SE.csv",format="%Y-%m-%d")
#head(d[,c("data","SE")])

#Acumular por SE e estacao
#df<-aggregate(d[,3:10],by=list(estacao=d$estacao,SE=d$SE),FUN=mean,na.rm=TRUE)
#head(df)
```

```


Abre dados weather underground (autor: Flavio)
-----------------
```{r}
gal<-callmongoclima("galeao") 
std <- callmongoclima("santosdumont")
afo <- callmongoclima("afonsos")
jac <- callmongoclima("jacarepagua")

d<- rbind(gal,std,afo,jac)
rm(gal,std,afo,jac)

# Atribuir SE
d$SE<-data2SE(d$data,file="../tabelas/SE.csv",format="%Y-%m-%d")

# Agregar por semana
df<-aggregate(d[,2:3],by=list(SE=d$SE,estacao=d$estacao),FUN=mean,na.rm=TRUE)

head(df)
tail(df)
```


```{r echo=FALSE}
#Estacao -> APS
listaAPS<-c("AP1","AP2.1","AP2.2","AP3.1","AP3.2","AP3.3","AP4","AP5.1","AP5.2","AP5.3")
dAP<-cbind(APS="AP1",df[df$estacao=="santosdumont",])
dAP<-rbind(dAP,cbind(APS="AP2.1",df[df$estacao=="santosdumont",]))
dAP<-rbind(dAP,cbind(APS="AP2.2",df[df$estacao=="santosdumont",]))
dAP<-rbind(dAP,cbind(APS="AP3.1",df[df$estacao=="galeao",]))
dAP<-rbind(dAP,cbind(APS="AP3.2",df[df$estacao=="galeao",]))
dAP<-rbind(dAP,cbind(APS="AP3.3",df[df$estacao=="galeao",]))
dAP<-rbind(dAP,cbind(APS="AP4",df[df$estacao=="jacarepagua",]))
dAP<-rbind(dAP,cbind(APS="AP5.1",df[df$estacao=="afonsos",]))
dAP<-rbind(dAP,cbind(APS="AP5.2",df[df$estacao=="afonsos",]))
dAP<-rbind(dAP,cbind(APS="AP5.3",df[df$estacao=="afonsos",]))
```

Salvar:
```{r echo=FALSE}
#outputfile = paste("../dados_limpos/temp_",max(dAP$SE),".csv",sep="")
```

```{r echo=FALSE}
#outputfile
```

```{r}
write.table(dAP,file="../dados_limpos/climasemanaRJ.csv",sep=",",row.names=FALSE)
```