ALERTA_DB_HOST=${ALERTA_DB_HOST}
ALERTA_DB_PORT=${ALERTA_DB_PORT}
ALERTA_DB_NAME=${ALERTA_DB_NAME}
ALERTA_DB_USER=${ALERTA_DB_USER}
ALERTA_DB_PASSWORD=${ALERTA_DB_PASSWORD}

ALERTA_OUT_DIR=${ALERTA_OUT_DIR}

ALERTA_REPORT_EPIWEEK=${ALERTA_REPORT_EPIWEEK}
ALERTA_WINDOW_WEEKS=${ALERTA_WINDOW_WEEKS}

ALERTA_DO_SCP=${ALERTA_DO_SCP} 
ALERTA_SCP_ENDPOINT=${ALERTA_SCP_ENDPOINT}
ALERTA_SCP_PATH=${ALERTA_SCP_PATH}
