backend: compose
env-file: .env

defaults:
  profile: dev
  project-name: alertadengueanalise-dev

profiles:
  dev:
    project-name: alertadengueanalise-dev
    env-file: .env
    config-path:
      - containers/compose.yaml
      - containers/compose-dev.yaml
    services:
      default:
        - analysis
      available:
        - name: analysis
  staging:
    project-name: alertadengueanalise-staging
    env-file: .env
    config-path:
      - containers/compose.yaml
      - containers/compose-staging.yaml
    services:
      default:
        - analysis
      available:
        - name: analysis
  prod:
    project-name: alertadengueanalise-prod
    env-file: .env
    config-path:
      - containers/compose.yaml
      - containers/compose-prod.yaml
    services:
      default:
        - analysis
      available:
        - name: analysis
