Organização dos dados do tweet RJ
===================================
Os dados de 2010 a 1-12-2013 estao agregados por semana, a partir dai sao diarios, esse script serve para construir
a serie historica ate 02062014.

```{r, echo=FALSE}
source("fun/data2SE.r")
```

Dados de 2014 por dia
----------------------

```{r}
arq<-"dados/tweets_01012014_02062014.csv"
d2dia<- read.table(arq,sep=",",header=T) 
d2dia<- d2dia[,c("data","rio")]
```

Cria variavel SE nos dados de 2014:
```{r}
d2dia$SE<-data2SE(d2dia$data,file="fun/SE.csv",format="%Y-%m-%d")      
tail(d2dia)
```

Antes de agregar, contar dias com dados na ultima semana epidemiologica
```{r}
ult<-sum(d2dia$SE==max(d2dia$SE))
ult
```

Agrega por semana os dados de 2014, removendo os dados incompletos finais:
```{r}
d2sem<-aggregate(d2dia$rio,by=list(SE=d2dia$SE),FUN=sum,na.rm=TRUE)
head(d2sem)
names(d2sem)[2]<-"tweets"
if (ult<7) d2sem<-d2sem[-(dim(d2sem)[1]),]
tail(d2sem)
```

Dados de 2010 a 1/12/2013 agregados por semana
---------------------------------------------

```{r}
d1<- read.csv("dados/tweets.csv")
names(d1)<-c("cidade","UF","data","tweets")
dRJ <- subset(d1,cidade=="Rio de Janeiro")
dRJ$data <- as.Date(dRJ$data, format="%Y-%m-%d")
```

Faltam dados de 2/12/2013 a 31/12/2013. Vou completar com NA por enquanto
```{r}
nas <- data.frame(cidade = rep("Rio de Janeiro",4), UF = rep("RJ",4), 
                  data=as.Date(c("2013-12-8","2013-12-15","2013-12-22","2013-12-29"), format="%Y-%m-%d")
                  ,tweets=rep(NA,4))
dRJ<-rbind(dRJ,nas)
```

Cria variavel SE:
```{r}
dRJ$SE<-data2SE(dRJ$data,file="fun/SE.csv",format="%Y-%m-%d")   
tail(dRJ)
```


Juntando
----------

```{r}
twRJ <- rbind(dRJ[,c("SE","tweets")],d2sem[,c("SE","tweets")])
```

**Gráfico**
```{r}
plot(twRJ$tweets,type="l",ylab="casos",xlab="semana",main="2011-2014")
abline(v=156,lty=3)
```

**salva dados**
```{r}
write.table(twRJ,file="tweet_201422.csv",sep=",",row.names=FALSE)
```