# PROJETO ALERTA DENGUE -------------------------------------
# Funcoes de calculo do alerta 
# Claudia Codeco 2015
# -----------------------------------------------------------

#setYellow --------------------------------------------------------------------
#'@title Define conditions to issue an alert of level Yellow.
#'@description Yellow is raised when environmental conditions required for
#'positive mosquito population growth are detected.
#'@param temp time series of temperature.
#'@param se sequence of epidemiological weeks.
#'@param tempcrit critical temperature.
#'@param lag count the number of weeks within the last lag weeks with conditions = TRUE.
#'@return data.frame with the week condition and the number of weeks within the 
#'last lag weeks with conditions = TRUE.
#'@examples
#'clima = getWU(stations = "SBRJ", var = "tmin")
#'yellow = setYellow(temp = clima$tmin, se = clima$SE,  tempcrit = 22) 
#'head(yellow)
#'x = 1:length(yellow$SE)
#'plot(x, yellow$temp, type="l", xlab= "weeks", ylab = "Temperature")
#'abline(h = 22, col =2)
#'points(x[yellow$yweek==1], yellow$temp[yellow$yweek==1], col="yellow", pch=16)

setYellow <- function(temp, se, tempcrit, lag=3){
  t1 <- as.numeric(temp > tempcrit)
  # 3 weeks accumulated condition
  le <- length(t1)
  ac <- t1[lag:le]
  for(i in 1:(lag-1)) ac <- ac+t1[(lag-i):(le-i)]
  data.frame(SE = se, temp = temp, yweek = t1, yacc = c(rep(NA,(lag-1)),ac))
}


#setOrange --------------------------------------------------------------------
#'@title Raise orange alert if sustained transmission is detected.
#'@description "Orange" is defined by effective reproductive number greater than 1. 
#'Rt must be computed before using this function.
#'@param obj object created by the Rt function.
#'@param pvalue probability of wrongly rejecting the hypothesis Rt > 1   
#'@param lag count the number of weeks within the last lag weeks with conditions = TRUE
#'@return data.frame with the week condition and the number of weeks within the 
#'last lag weeks with conditions = TRUE
#'@examples
#'res <- getCases(city = c(330455), withdivision = FALSE) # Rio de Janeiro
#'resd <- aggrbylocality(d = res, locality="AP1") # Rio de Janeiro
#'resfit <- adjustIncidence(se = res$SE, y = res$casos)
#'rtnorm<-Rt(y = resfit$tcasesmed, se = resfit$SE, gtdist="normal", meangt=3, sdgt = 1)
#'ora = setOrange(obj = rtnorm, pvalue = 0.9, lag= 3) 
#'head(ora)
#'x = 1:length(ora$SE)
#'plot(x, ora$Rt, type="l", xlab= "weeks", ylab = "Rt")
#'lines(x, ora$upr, lty = 3)
#'lines(x, ora$lwr, lty = 3)
#'abline(h = 1, col =2)
#'points(x[ora$oweek==1], ora$Rt[ora$oweek==1], col="orange", pch=16)

setOrange <- function(obj, pvalue = 0.9, lag=3){
  
  if(!("p1" %in% names(obj))) stop("obj must be created by an Rt function")
  
  obj$oweek <- as.numeric(obj$p1 > pvalue)
  
  # lag weeks accumulated condition
  le <- dim(obj)[1]
  ac <- obj$oweek[lag:le]
  for(i in 1:(lag-1)) ac <- ac+obj$oweek[(lag-i):(le-i)]
  obj$oacc <- c(rep(NA,(lag-1)),ac)
  
  return(obj)
}


#setRed --------------------------------------------------------------------
#'@title Raise red alert if incidence reaches above a threshold. 
#'@description "Red" indicates high dengue incidence, defined by a threshold provided 
#'by the user. The WHO recommends 300 per 100.000. 
#'@param obj case count dataset generated by the getcase (ajusted or not).
#'@param pop population of the area.
#'@param adjust TRUE if adjusting incidence is required. FALSE if not.   
#'@param ccrit incidence threshold (per 100.000).
#'@param lag count the number of weeks within the last lag weeks with conditions = TRUE.
#'@return data.frame with the week condition and the number of weeks within the 
#'last lag weeks with conditions = TRUE
#'@examples
#'res = getCases(city = c(330455), withdivision = TRUE) # Rio de Janeiro
#'resd = aggrbylocality(d = res, locality="AP1") # Rio de Janeiro
#'resfit<-adjustIncidence(se = resd$SE, y = resd$casos)
#'red = setRed(obj = resfit, pop = 30000, ccrit = 10, lag=3)
#'tail(red)
#'x = 1:length(red$SE)
#'plot(x, red$inc, type="l", xlab= "weeks", ylab = "incidence")
#'abline(h = 10, col =2)
#'points(x[red$rweek==1], red$inc[red$rweek==1], col="red", pch=16)

setRed <- function(obj, pop, ccrit=100, lag=3){
  
  if("tcasesICmin" %in% names(obj)) {}
  else stop("please carry out the incidence adjustment first.")
      
  inc <- obj$tcasesICmin / pop * 100000
  i1 <- inc > ccrit
  # 3 weeks accumulated condition
  le <- length(i1)
  ac <- i1[lag:le]
  for(i in 1:(lag-1)) ac <- ac+i1[(lag-i):(le-i)]
  
  obj$inc <- inc
  obj$rweek <- as.numeric(i1)
  obj$racc <- c(rep(NA,(lag-1)),ac)
  
  return(obj)
  }



#classify ------------------------------------------------------------
#'@title Classifies the disease time series into transmission levels.
#'@description This function receives the time series inputs (cases, tweets, 
#'climate) and return levels of alert (1 (low) to 4 (high)). It will run the
#' set color functions and them combine them hierarchically.    
#'@param yellow object from setyellow function.
#'@param orange object from setorange function.
#'@param red object from setred function.
#'@return data.frame with
#'@examples
#' #This is the whole sequence of the alert. Getting data:
#'res <- getCases(city = c(330455), withdivision = TRUE) # get case data from Rio de Janeiro
#'resd <- aggrbylocality(d = res, locality="AP1") # case data from a locality in Rio de Janeiro
#'tweet <- getTweet(city = c(330455)) # Rio de Janeiro # get tweeter data
#'clima <- getWU(stations = 'SBRJ', var = "tmin") # get locality's tmin from local meteorological station
#' #Adjust incidence
#'adjcase <- adjustIncidence(se = resd$SE, y = resd$casos)
#' # Calculate Rt
#'rtnorm<-Rt(y = resfit$tcasesmed, se = resfit$SE, gtdist="normal", meangt=3, sdgt = 1)
#' #Calculate each level
#'yellowalert <- setYellow(temp = clima$tmin, se = clima$SE, tempcrit = 22)
#'orangealert <- setOrange(obj = resd, pvalue = 0.9, lag= 3) 
#'redalert <- setRed(se = adjcase$SE, y = adjcase$tcasesICmin, adjust=FALSE, pop = 30000, 
#'                    ccrit = 100, lag=3)
#' # green - yellow levels only 
#'resu <- classify(yel = yellowalert) # with only green-yellow levels
#'tail(resu)
#'x = 1:length(resu$temp)
#'plot(x,resu$temp, type="l", xlab= "weeks", ylab = "temp")
#'points(x[resu$level==2], resu$temp[resu$level==2], col="yellow",pch=16)
#' # all four levels
#'resu <- classify(yel = yellowalert, ora = orangealert, red = redalert) 




classify <- function(yel, ora=c(), red=c(), turnoff = c(3000,3,3,3)){
  
  # defining the number of levels from the input
  if (is.null(yel)) stop("calculate setYellow")
  if (is.null(yel) == FALSE & is.null(ora) == TRUE & is.null(red) == TRUE){
    print("only green - yellow levels calculated")
    ncol = 2
    yel$level <- NA
    les = dim(yel)[1]
    inerciaon = max(yel$yacc) # the number of weeks until the system turns to yellow
    yel$level[intersect(6:les,which(yel$yacc<3))] <-  1 # first color
    yel$level[intersect(6:les,which(yel$yacc>=3))]<-  2 # second color
    inerciaoff = turnoff[2] # number of weeks not turningoff once on
    for (i in 1:inerciaoff) yel$level[intersect(6:les,which(yel$yacc>=3)+i)] <- 2   
    }
  if (is.null(yel) == FALSE & is.null(ora) == FALSE & is.null(red) == FALSE){
    ncol = 4
  }
    
  yel
}

