name: alertadengueanalise
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - git
  - postgresql

  - pkg-config
  - make
  - cmake
  - c-compiler
  - cxx-compiler
  - gfortran
  - libgcc

  - zlib
  - libpng
  - libjpeg-turbo
  - freetype
  - fontconfig
  - harfbuzz
  - fribidi
  - cairo
  - pango
  - libxml2
  - libcurl
  - openssl
  - gmp
  - mpfr

  - r-base

  - r-foreign
  - r-forecast
  - r-rpostgresql
  - r-xtable
  - r-zoo
  - r-tidyverse
  - r-assertthat
  - r-futile.logger
  - r-gridextra
  - r-ggridges
  - r-dbi
  - r-jsonlite
  - r-optparse
  - r-remotes
  - r-testthat

  - r-rcurl
  - r-curl
  - r-gmp
  - r-rmpfr

  - pandoc
  - r-knitr
  - r-rmarkdown
  - r-bslib
  - r-fontawesome
  - r-jquerylib
  - r-shiny
  - r-htmlwidgets
  - r-miniui
  - r-profvis
  - r-pkgdown
  - r-rcmdcheck
  - r-usethis
  - r-miceadds
  - r-units
  - r-s2
  - r-sf
  - r-fmesher
  - pip:
      - click>=8.1,<9
      - containers-sugar >=1.19,<2.0
      - makim==1.27.0
