Analise do atraso de notificacao do SINAN Dengue RJ
====================================================

```{r, echo=FALSE}
require(foreign)
```

Dados de 2010 a 2013
```{r}
d10 <- read.dbf(file="../../dados_brutos/sinan/old/Dengue2010_BancoSINAN16_04_2012_v09012014.dbf")[,c("DT_NOTIFIC","SEM_NOT","NU_ANO","DT_SIN_PRI","DT_DIGITA","SEM_PRI")]
d11 <- read.dbf(file="../../dados_brutos/sinan/old/Dengue2011_BancoSINAN14_10_2013_v09012014.dbf")[,c("DT_NOTIFIC","SEM_NOT","NU_ANO","DT_SIN_PRI","DT_DIGITA","SEM_PRI")]
d12 <- read.dbf(file="../../dados_brutos/sinan/old/Dengue2012_BancoSINAN09_09_2013_v09012014.dbf")[,c("DT_NOTIFIC","SEM_NOT","NU_ANO","DT_SIN_PRI","DT_DIGITA","SEM_PRI")]
d13 <- read.dbf(file="../../dados_brutos/sinan/old/Dengue2013_BancoSINAN30_12_2013.dbf")[,c("DT_NOTIFIC","SEM_NOT","NU_ANO","DT_SIN_PRI","DT_DIGITA","SEM_PRI")]
d14 <- read.dbf(file="../../dados_brutos/sinan/Dengue - Oswaldo 15.10.dbf")[,c("DT_NOTIFIC","SEM_NOT","NU_ANO","DT_SIN_PRI","DT_DIGITA","SEM_PRI")]

d<-rbind(d10,d11,d12,d13,d14)
rm(d10,d11,d12,d13,d14)
n1<-dim(d)[1]
```



**Variaveis de tempo**
```{r}
summary(d$DT_NOTIFIC)
summary(d$DT_SIN_PRI)
summary(d$DT_DIGITA)

# Data primeiro sintoma -
head(sort(d$DT_SIN_PRI),n=50) # vou remover todas anteriores a 2010

d<-d[-which(d$DT_SIN_PRI<"2009-12-31"),]
summary(d$DT_SIN_PRI)
n2 <- dim(d)[1]
n1-n2
```


**tempo ate notificar** 
```{r echo=FALSE}
d$tnotif<-as.numeric(d$DT_NOTIFIC-d$DT_SIN_PRI)
quantile(d$tnotif,probs=seq(0,1,by=0.05))
```

**tempo ate digitar** 
```{r echo=FALSE}
d$diasdigit<-as.numeric(d$DT_DIGITA-d$DT_NOTIFIC)
summary(d$diasdigit)

par(mfrow=c(1,1),mar=c(5,5,3,3))
d<-na.omit(d)
range(d$diasdigit)
freq<-hist(d$tdigit,breaks=seq(0,700,by=7))
freq$counts/sum(freq$counts)
plot(cumsum(freq$counts)/sum(freq$counts),type="s",ylab="tempo ate digitar",xlab="semana")

cumfreq<-cumsum(freq$counts)/sum(freq$counts)
cumfreq[1:12]

```

**Serie temporal **

```{r echo=FALSE}
st <- aggregate(d$SEM_PRI,by=list(d$SEM_PRI),FUN=length)
names(st)<-c("SE","casos")
st$SE<-as.numeric(as.character(st$SE))
tail(st)

stdg<-aggregate(d$diasdigit,by=list(d$SEM_PRI),FUN=median,na.rm=TRUE)
names(stdg)<-c("SE","tdigit")
stdg$SE<-as.numeric(as.character(stdg$SE))
tail(stdg)

dd<-merge(st,stdg)
dd<-dd[order(dd$SE),]
tail(dd)
plot(dd$SE,dd$tdigit,xlab="Ano",ylab="atraso digitação")
dd$ano<-trunc(dd$SE/100)
head(dd)

par(mfrow=c(2,1),mar=c(3,5,1,1))
boxplot(tdigit~ano,data=dd,ylab="atraso digitação",ylim=c(0,40))
boxplot(casos~ano,data=dd,ylab="# notificações")


```


Analise a partir de 2011
```{r}
ddd<-subset(dd,ano>2010)
par(mfrow=c(2,1),mar=c(3,5,1,1))
boxplot(tdigit~ano,data=ddd,ylab="atraso digitação",ylim=c(0,40))
boxplot(casos~ano,data=ddd,ylab="# notificações")

plot(ddd$casos,ddd$tdigit) # pouca correlacao a quantidade de casos
tapply(ddd$tdigit,ddd$ano,quantile)

```

Distribuicao do tempo de atraso
```{r}
par(mfrow=c(2,2))
plot(density(ddd$tdigit[ddd$ano==2011]),main=2011)
plot(density(ddd$tdigit[ddd$ano==2012]),main=2012)
plot(density(ddd$tdigit[ddd$ano==2013]),main=2013)
plot(density(ddd$tdigit[ddd$ano==2014]),main=2014)
```

```{r}
pacf(ddd$tdigit)
```

**Reconstruindo os dados removendo as digitacoes tardias**
```{r}
d1s <- subset(d,tdigit<8)
d2s <- subset(d,tdigit<15)
d3s <- subset(d,tdigit<22)

# apenas os casos com ate uma semana de atraso
st1 <- aggregate(d1s$SEM_PRI,by=list(d1s$SEM_PRI),FUN=length)
names(st1)<-c("SE","casos")
st1$SE<-as.numeric(as.character(st1$SE))
tail(st1)

#apenas casos com ate duas semanas de atraso
st2 <- aggregate(d2s$SEM_PRI,by=list(d2s$SEM_PRI),FUN=length)
names(st2)<-c("SE","casos")
st2$SE<-as.numeric(as.character(st2$SE))
tail(st2)

#apenas casos com ate 3 semanas de atraso
st3 <- aggregate(d3s$SEM_PRI,by=list(d3s$SEM_PRI),FUN=length)
names(st3)<-c("SE","casos")
st3$SE<-as.numeric(as.character(st3$SE))
tail(st3)


par(mfrow=c(1,1))
plot(st1$casos,type="l",ylim=c(0,max(st$casos)),ylab="casos notificados",xlab="tempo",col="red")
lines(st2$casos,col="green")
lines(st3$casos,col="blue")
lines(st$casos,col="black",lwd=2)
legend(150,8000,c("ate 1 semana atraso","2 semanas","3 semanas","todos"),cex=0.8,lty=1,col=c("red","green","blue","black"))
title("sem correção para atraso de digitação")
```

Aplicando a correção

```{r}
par(mfrow=c(1,1))
plot(st1$casos/0.317,type="l",ylim=c(0,max(st$casos)),ylab="casos notificados",xlab="tempo",col="red")
lines(st2$casos/0.531,col="green")
lines(st3$casos/0.652,col="blue")
lines(st$casos,col="black",lty=2,lwd=2)
legend(150,8000,c("ate 1 semana atraso","2 semanas","3 semanas","todos"),cex=0.8,lty=1,col=c("red","green","blue","black"))
title("com correção para atraso de digitação")

```


