Gera Relatorio
========================================================
Ainda em fase preliminar

```{r echo=FALSE}
#aRJ <- paste("../",aRJ,sep="")
alertaRJ <- read.csv(aRJ)
#aAP <- paste("../",aAP,sep="")
alertaAP <- read.csv(aAP)

```

Alerta MRJ
----------
```{r echo=FALSE}
tail(aRJ)
```

```{r echo=FALSE}
par(mfrow=c(4,1),mar=c(0,0,0,0))
plot(alertaRJ$casos,type='l',axes=F)
text(10,0.9*max(alertaRJ$casos),"Temp>24",cex=1.4)
abline(v=which(alertaRJ$alertaTemp==1),col=655,lwd=1.2)
plot(alertaRJ$casos,type='l',axes=F)
text(10,0.9*max(alertaRJ$casos),"Rt>1",cex=1.4)
abline(v=which(alertaRJ$alertaRt1==1),col="orange",lwd=1.2)
plot(alertaRJ$casos,type='l',axes=F)
abline(v=which(alertaRJ$alertaCasos==1),col="red",lwd=1.2)
text(20,0.9*max(alertaRJ$casos),"casos>media+2sd",cex=1.4)
plot(alertaRJ$tweets,type='l',axes=F)
text(10,0.9*max(alertaRJ$tweets),"tweets",cex=1.4)
```

APS
-----------

```{r echo=FALSE}
listaAP <- unique(alertaAP$APS)
plot.alerta<-function(ap){
      par(mfrow=c(4,1),mar=c(0,0,0,0))
      plot(alertaAP$casos[alertaAP$APS==ap],type='l',axes=F)
      text(10,0.9*max(alertaAP$casos[alertaAP$APS==ap]),"Temp>24",cex=1.4)
      text(80,0.9*max(alertaAP$casos[alertaAP$APS==ap]),labels=as.character(ap),cex=1.4)
      abline(v=which(alertaAP$alertaTemp[alertaAP$APS==ap]==1),col=655,lwd=1.2)
      plot(alertaAP$casos[alertaAP$APS==ap],type='l',axes=F)
      text(10,0.9*max(alertaAP$casos[alertaAP$APS==ap]),"Rt>1",cex=1.4)
      abline(v=which(alertaAP$alertaRt1[alertaAP$APS==ap]==1),col="orange",lwd=1.2)
      plot(alertaAP$casos[alertaAP$APS==ap],type='l',axes=F)
      abline(v=which(alertaAP$alertaCasos[alertaAP$APS==ap]==1),col="red",lwd=1.2)
      text(20,0.9*max(alertaAP$casos[alertaAP$APS==ap]),"casos>media+2sd",cex=1.4)
      plot(alertaAP$tweets[alertaAP$APS==ap],type='l',axes=F)
      text(10,0.9*max(alertaAP$tweets[alertaAP$APS==ap]),"tweets",cex=1.4)
}
```


```{r echo=FALSE}
for(i in 1:10) {
      plot.alerta(listaAP[i])
}
```

